// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKluGWa1ye7V--poyOJm_UZ8g3PI3kxAk',
    appId: '1:47408515610:web:6c176a32434c1c454cdfa3',
    messagingSenderId: '47408515610',
    projectId: 'raychat-9bd07',
    authDomain: 'raychat-9bd07.firebaseapp.com',
    storageBucket: 'raychat-9bd07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7jo0iN2JEIsxFDKbIwXXyUzEEDWJOh_Y',
    appId: '1:47408515610:android:a5d334c41d89755f4cdfa3',
    messagingSenderId: '47408515610',
    projectId: 'raychat-9bd07',
    storageBucket: 'raychat-9bd07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVGYA5tk5z2plHLYq03J6gGAZ0X-pWHSs',
    appId: '1:47408515610:ios:60539cd7aaaa0f0a4cdfa3',
    messagingSenderId: '47408515610',
    projectId: 'raychat-9bd07',
    storageBucket: 'raychat-9bd07.appspot.com',
    iosClientId: '47408515610-baidj2isl9kn4ks6ljfhbef2re385l4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.raychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVGYA5tk5z2plHLYq03J6gGAZ0X-pWHSs',
    appId: '1:47408515610:ios:60539cd7aaaa0f0a4cdfa3',
    messagingSenderId: '47408515610',
    projectId: 'raychat-9bd07',
    storageBucket: 'raychat-9bd07.appspot.com',
    iosClientId: '47408515610-baidj2isl9kn4ks6ljfhbef2re385l4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.raychat',
  );
}
